name: mujoco
channels:
  - defaults
dependencies:
  - ca-certificates=2024.12.31=haa95532_0
  - openssl=3.0.15=h827c3e9_0
  - pip=24.2=py39haa95532_0
  - python=3.9.21=h8205438_1
  - setuptools=75.1.0=py39haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - vc=14.40=haa95532_2
  - vs2015_runtime=14.42.34433=h9531ae6_2
  - wheel=0.44.0=py39haa95532_0
  - pip:
      - absl-py==2.1.0
      - apscheduler==3.11.1
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - dynamixel-sdk==4.0.3
      - etils==1.5.2
      - farama-notifications==0.0.4
      - feetech-servo-sdk==1.0.0
      - fonttools==4.57.0
      - fsspec==2024.12.0
      - glfw==2.8.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==1.0.0
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - jbigkit-py==2.1.4
      - keyboard==0.13.5
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - mpmath==1.3.0
      - mujoco==3.2.7
      - numpy==1.23.5
      - opencv-python==4.11.0.86
      - packaging==25.0
      - pillow==11.2.1
      - pyopengl==3.1.9
      - pyparsing==3.2.3
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - requests==2.32.3
      - scipy==1.13.1
      - six==1.17.0
      - sympy==1.14.0
      - torch==1.13.0+cpu
      - torchaudio==0.13.0+cpu
      - torchvision==0.14.0+cpu
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - tzlocal==5.3.1
      - urllib3==2.4.0
      - zipp==3.21.0
prefix: D:\software\Anaconda\envs\mujoco
